from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path

CATEGORY_NAMES = ["person", "rider", "motorcycle", "car"]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--source-root",
        default=r"E:\毕设\code\visnir-det\data\iddaw_fog_smoke_medium",
        help="Root directory of the paired smoke dataset generated by visnir-det.",
    )
    parser.add_argument(
        "--output-root",
        default=r"E:\毕设\code\datasets\iddaw_fog_yolov11_rgbnir",
        help="Target YOLOv11 RGB+NIR dataset root.",
    )
    parser.add_argument(
        "--clean",
        action="store_true",
        help="Remove the output directory before exporting.",
    )
    return parser.parse_args()


def ensure_dirs(root: Path) -> None:
    for relative in (
        Path("visible/train"),
        Path("visible/val"),
        Path("nir/train"),
        Path("nir/val"),
        Path("meta"),
    ):
        (root / relative).mkdir(parents=True, exist_ok=True)


def yolo_line(annotation: dict[str, object], width: int, height: int) -> str:
    x, y, w, h = annotation["bbox"]
    cx = (float(x) + float(w) / 2.0) / float(width)
    cy = (float(y) + float(h) / 2.0) / float(height)
    bw = float(w) / float(width)
    bh = float(h) / float(height)
    category = int(annotation["category_id"]) - 1
    return f"{category} {cx:.6f} {cy:.6f} {bw:.6f} {bh:.6f}"


def export_split(source_root: Path, output_root: Path, split: str) -> dict[str, int]:
    annotation_path = source_root / "annotations" / f"{split}.json"
    payload = json.loads(annotation_path.read_text(encoding="utf-8"))
    visible_split_dir = output_root / "visible" / split
    nir_split_dir = output_root / "nir" / split

    image_count = 0
    label_count = 0

    for sample in payload["samples"]:
        width = int(sample["width"])
        height = int(sample["height"])
        vis_src = source_root / Path(sample["vis_path"])
        nir_src = source_root / Path(sample["nir_path"])
        sample_stem = str(sample["sample_id"])

        if not vis_src.exists() or not nir_src.exists():
            raise FileNotFoundError(f"Missing paired image for sample {sample['sample_id']}")

        shared_image_name = f"{sample_stem}{vis_src.suffix.lower()}"
        shared_label_name = f"{sample_stem}.txt"
        vis_dst = visible_split_dir / shared_image_name
        nir_dst = nir_split_dir / shared_image_name
        vis_label_dst = visible_split_dir / shared_label_name
        nir_label_dst = nir_split_dir / shared_label_name

        shutil.copy2(vis_src, vis_dst)
        shutil.copy2(nir_src, nir_dst)

        lines = [yolo_line(annotation, width, height) for annotation in sample["annotations"]]
        label_text = "\n".join(lines)
        vis_label_dst.write_text(label_text, encoding="utf-8")
        nir_label_dst.write_text(label_text, encoding="utf-8")

        image_count += 2
        label_count += 2

    return {"images": image_count, "labels": label_count, "samples": len(payload["samples"])}


def main() -> None:
    args = parse_args()
    source_root = Path(args.source_root).resolve()
    output_root = Path(args.output_root).resolve()

    if args.clean and output_root.exists():
        shutil.rmtree(output_root)
    ensure_dirs(output_root)

    train_stats = export_split(source_root, output_root, "train")
    val_stats = export_split(source_root, output_root, "val")
    report = {
        "source_root": str(source_root),
        "output_root": str(output_root),
        "categories": CATEGORY_NAMES,
        "splits": {
            "train": train_stats,
            "val": val_stats,
        },
    }
    (output_root / "meta" / "export_report.json").write_text(
        json.dumps(report, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    print(json.dumps(report, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
